### ISSUE TITLE
Is it support to add current date time in log file name?

### ISSUE THREAD

**Issue by EmptyChan** [BNMetrics/logme#4]
### For example
![log name](https://user-images.githubusercontent.com/13757028/46117624-374dbd00-c1d0-11e8-98e1-5c7cd6ebb3c4.png)

>  Like this

![image](https://user-images.githubusercontent.com/13757028/46117846-7c262380-c1d1-11e8-916e-3260c5320172.png)

Hi,  BNMerics,

Thanks to build this great log Python library. But I am puzzled that I want the log file can be created with date time field. 

Sorry, my english is poor.

Thanks again.

**Comment by Dectinc** [comment]
Hi @EmptyChan 
Try using TimeRotatingFileHandler, you can add the following configuration in `logme` section of you `logme.ini`

```
file = 
	type: TimedRotatingFileHandler
	active: True
	level: INFO
	when: MIDNIGHT
	filename: log/to/path
```

**Comment by BNMetrics** [comment]
Hi @EmptyChan, As @Dectinc had mentioned, TimeRotatingFileHandler would probably be the best for your need! :)

@Dectinc, Thanks so much for answering the question!
