### ISSUE TITLE
Cannot import logme on ubuntu 16.04

### ISSUE THREAD

**Issue by strimpak** [BNMetrics/logme#6]
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

# pip install --upgrade logme
Requirement already up-to-date: logme in /usr/local/lib/python3.5/dist-packages (1.3.0)
Requirement already satisfied, skipping upgrade: bnmutils in /usr/local/lib/python3.5/dist-packages (from logme) (1.0.2)
Requirement already satisfied, skipping upgrade: click in /usr/local/lib/python3.5/dist-packages (from logme) (7.0)

# python3.5
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logme
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/logme/__init__.py", line 53
    raise MisMatchScope(f"{callable_} is a class, cannot be assigned to a '{scope}' scope")
                                                                                         ^
SyntaxError: invalid syntax
>>>

**Comment by BNMetrics** [comment]
Hi @strimpak ,
It looks like there is a version mismatch error.
I saw you have python3.5.2 on Ubuntu xenial, and this is the default python3. However, currently logme only supports python3.6 and up. :(

I'm sorry... :(

**Comment by strimpak** [comment]
It seems to be a pip issue, that installed this package successfully. I saw that in pipfile has python version 3.6 .

**Comment by BNMetrics** [comment]
Definitely, I think I'm going to need to specify in the setup to python 3.6 and up. Thanks for flagging this issue! :+1:

**Comment by BNMetrics** [comment]
Hello @strimpak,

I have changed the `python_requires` in setup.py. Now it should only be installed with python3.6. :)

Thanks so much for flagging this issue. Let me know if this works for you. 
I will close this for now. :)
